# Lecture 2: Type Stability

## Defeating type inference: Type instabilities

To get good performance, there are some fairly simple rules that you need to follow in Julia code to avoid defeating the compiler's type inference.   See also the [performance tips section of the Julia manual](http://docs.julialang.org/en/stable/manual/performance-tips/).

Three of the most important are:

* Don't use (non-constant) global variables in critical code — put your critical code into a function (this is good advice anyway, from a software-engineering standpoint).  The compiler assumes that a **global variable can change type at any time**, so it is always stored in a "box", and "taints" anything that depends on it.

* Local variables should be "type-stable": **don't change the type of a variable inside a function**.  Use a new variable instead.

* Functions should be "type-stable": **a function's return type should only depend on the argument types, not on the argument values**.

To diagnose all of these problems, the `@code_warntype` macro that we used above is your friend.  If it labels any variables (or the function's return value) as `Any` or `Union{...}`, it means that the compiler couldn't figure out a precise type.

The third point, type-stability of functions, leads to lots of important but subtle choices in library design.  For example, consider the (built-in) `sqrt(x)` function, which computes $\sqrt{x}$:

In [1]:
sqrt(4)

2.0

You might think that `sqrt(-1)` should return $i$ (or `im`, in Julia syntax).  (Matlab's `sqrt` function does this.)  Instead, we get:

In [2]:
sqrt(-1)

DomainError: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [3]:
sqrt(-1 + 0im)

0.0 + 1.0im

Why did Julia implement `sqrt` in this silly way, throwing an error for negative arguments unless you add a zero imaginary part?  Any reasonable person wants an imaginary result from `sqrt(-1)`, surely?

The problem is that defining `sqrt` to return an imaginary result from `sqrt(-1)` would **not be type stable**: `sqrt(x)` would return a real result for non-negative real `x`, and a complex result for negative real `x`, so the **return type would depend on the value of `x`** and **not just its type.**

That would defeat type inference, not just for the `sqrt` function, but for **anything the sqrt function touches**.  Unless the compiler can somehow figure out `x ≥ 0`, it will have to either store the result in a "box" or compile two branches of the result.  Let's see how that works by defining our own square-root function:

In [4]:
mysqrt(x::Complex) = sqrt(x)
mysqrt(x::Real) = x < 0 ? sqrt(complex(x)) : sqrt(x)

mysqrt (generic function with 2 methods)

This definition is an example of Julia's [multiple dispatch style](http://docs.julialang.org/en/stable/manual/methods/), which in some sense is a generalization of object-oriented programming but focuses on "verbs" (functions) rather than nouns.  We will discuss this more in a later lecture.

The `::Complex` and `::Real` are argument-type declarations.  Such declarations are **not related to performance**, but instead **act as a "filter"** to allow us to have one version of `mysqrt` for complex arguments and another for real arguments.

In [5]:
mysqrt(2)

1.4142135623730951

In [6]:
mysqrt(-2)

0.0 + 1.4142135623730951im

In [7]:
mysqrt(-2+0im)

0.0 + 1.4142135623730951im

Looks great, right?  But let's see what happens to type inference in a function that calls `mysqrt` instead of `sqrt`:

In [18]:
slowfun(x) = mysqrt(x) + 1
@code_warntype slowfun(2.0)

Variables
  #self#::Core.Compiler.Const(slowfun, false)
  x::Float64

Body::Union{Complex{Float64}, Float64}
1 ─ %1 = Main.mysqrt(x)::Union{Complex{Float64}, Float64}
│   %2 = (%1 + 1)::Union{Complex{Float64}, Float64}
└──      return %2


Because the compiler **doesn't know at compile-time that x is positive** (at compile-time it **uses only types, not values**, it doesn't know whether the result is real (`Float64`) or complex (`Complex{Float64}`) and has to store it in a "box".  This kills performance.

In [9]:
i = 3

3

In [10]:
typeof(i)

Int64

In [11]:
i^100000

-3665183052406099839

In [12]:
i = typemax(Int)

9223372036854775807

In [13]:
i + 1

-9223372036854775808

## Defining our own types

Let's define our own type to represent a **"point" in two dimensions**.  Each point will have an $(x,y)$ location.  So that we can use the points with our `sum` functions above, we'll also define `+` and `zero` functions to do the obvious **vector addition**.

One such definition in Julia is:

In [14]:
mutable struct Point1
    x
    y
end
Base.:+(p::Point1, q::Point1) = Point1(p.x + q.x, p.y + q.y)
Base.zero(::Type{Point1}) = Point1(0,0)

Point1(3,4)

Point1(3, 4)

In [15]:
Point1(3,4) + Point1(5,6)

Point1(8, 10)

Our type is very generic, and can hold any type of `x` and `y` values:

In [16]:
Point1(3.7, 4+5im)

Point1(3.7, 4 + 5im)

Perhaps too generic:

In [17]:
Point1("x", [3,4,5])

Point1("x", [3, 4, 5])

Since `x` and `y` can be *anything*, they must be **pointers to "boxes"**.  This is **bad news for performance**.

A `mutable struct` is *mutable*, which means we can create a `Point1` object and then change `x` or `y`:

In [18]:
p = Point1(3,4)

Point1(3, 4)

In [19]:
p.x = 7
p

Point1(7, 4)

In [20]:
q = p

Point1(7, 4)

This means that every reference to a `Point1` object must be a *pointer* to an object stored elsewhere in memory, because *how else would we "know" when an object changes?*  Furthermore, an **array of `Point1` objects must be an array of pointers** (which is **bad news for performance** again):

In [21]:
P = [p,p,p]

3-element Array{Point1,1}:
 Point1(7, 4)
 Point1(7, 4)
 Point1(7, 4)

In [22]:
P

3-element Array{Point1,1}:
 Point1(7, 4)
 Point1(7, 4)
 Point1(7, 4)

In [23]:
Q = [deepcopy(p), deepcopy(p)]

2-element Array{Point1,1}:
 Point1(7, 4)
 Point1(7, 4)

In [24]:
p.x = -3
P

3-element Array{Point1,1}:
 Point1(-3, 4)
 Point1(-3, 4)
 Point1(-3, 4)

In [25]:
Q

2-element Array{Point1,1}:
 Point1(7, 4)
 Point1(7, 4)

Let's test this out by creating an array of `Point1` objects and summing it.  Ideally, this would be about twice as slow as summing an equal-length array of numbers, since there are twice as many numbers to sum.  But because of all of the boxes and pointer-chasing, it should be far slower.

To create the array, we'll call the `Point1(x,y)` constructor with our array `a`, using Julia's ["dot-call" syntax](http://docs.julialang.org/en/stable/manual/functions/#dot-syntax-for-vectorizing-functions) that applies a function "element-wise" to arrays:

In [26]:
a = rand(10^7)
a1 = Point1.(a, a)

10000000-element Array{Point1,1}:
 Point1(0.28993068469663097, 0.28993068469663097)
 Point1(0.9520665822042185, 0.9520665822042185)
 Point1(0.10257433930297655, 0.10257433930297655)
 Point1(0.1864134983639525, 0.1864134983639525)
 Point1(0.3026818056611691, 0.3026818056611691)
 Point1(0.47915556868984055, 0.47915556868984055)
 Point1(0.4891262853293532, 0.4891262853293532)
 Point1(0.2781632850254554, 0.2781632850254554)
 Point1(0.6820873616356449, 0.6820873616356449)
 Point1(0.2406469590612701, 0.2406469590612701)
 Point1(0.7593836814765698, 0.7593836814765698)
 Point1(0.27902825958412136, 0.27902825958412136)
 Point1(0.9269892600101655, 0.9269892600101655)
 ⋮
 Point1(0.7655473526547134, 0.7655473526547134)
 Point1(0.45252985394422285, 0.45252985394422285)
 Point1(0.2223952449661586, 0.2223952449661586)
 Point1(0.20598062505637427, 0.20598062505637427)
 Point1(0.141356841726749, 0.141356841726749)
 Point1(0.39005950533913425, 0.39005950533913425)
 Point1(0.976272262977363, 0.9762722629

In [20]:
import Pkg

In [31]:
Pkg.add("Compat")

   Updating registry at `C:\Users\Victor\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`


Fetching: [========================================>]  100.0 %.0 %

  Resolving package versions...
   Updating `C:\Users\Victor\.julia\environments\v1.4\Project.toml`
  [34da2185] + Compat v3.12.0
   Updating `C:\Users\Victor\.julia\environments\v1.4\Manifest.toml`
 [no changes]


In [21]:
using BenchmarkTools, Compat

In [33]:
@btime sum($a1)

  849.857 ms (29999997 allocations: 610.35 MiB)


Point1(4.999572304980365e6, 4.999572304980365e6)

The time is at least **50× slower** than we would like, but consistent with our other timing results on "boxed" values from last lecture.

### An imperfect solution: A concrete immutable type

We can avoid these two problems by:

* Declare the types of `x` and `y` to be *concrete* types, so that they don't need to be pointers to boxes.
* Declare our Point to be an [immutable](https://en.wikipedia.org/wiki/Immutable_object) type (`x` and `y` cannot change), so that Julia is not forced to make every reference to a Point into a pointer: just `struct`, not `mutable struct`:

In [39]:
struct Point2
    x::Float64
    y::Float64
end
Base.:+(p::Point2, q::Point2) = Point2(p.x + q.x, p.y + q.y)
Base.zero(::Type{Point2}) = Point2(0.0,0.0)

Point2(3,4)

Point2(3.0, 4.0)

In [40]:
Point2(3,4) + Point2(5,6)

Point2(8.0, 10.0)

In [52]:
p = Point2(3,4)
P = [p,p,p]

3-element Array{Point2,1}:
 Point2(3.0, 4.0)
 Point2(3.0, 4.0)
 Point2(3.0, 4.0)

In [53]:
p.x = 6 # gives an error since p is immutable

LoadError: type Point2 is immutable

In [54]:
sizeof(P) / length(P)

16.0

If this is working as we hope, then summation should be much faster:

In [55]:
a2 = Point2.(a,a)
@btime sum($a2)

  11.792 ms (0 allocations: 0 bytes)


Point2(5.000915878780597e6, 5.000915878780597e6)

Now the time is **only about 10ms**, only slightly more than twice the cost of summing an array of individual numbers of the same length!

Unfortunately, we paid a big price for this performance: our `Point2` type only works with *a single numeric type* (`Float64`), much like a C implementation.

### The best of both worlds: Parameterized immutable types

How do we get a `Point` type that works for *any* type of `x` and `y`, but at the same time allows us to have an array of points that is concrete and homogeneous (every point in the array is forced to be the same type)?  At first glance, this seems like a contradiction in terms.

The answer is not to define a *single* type, but rather to **define a whole family of types** that are *parameterized* by the type `T` of `x` and `y`.  In computer science, this is known as [parametric polymorphism](https://en.wikipedia.org/wiki/Parametric_polymorphism).  (An example of this can be found in [C++ templates](https://en.wikipedia.org/wiki/Template_%28C%2B%2B%29).)

In Julia, we will define such a family of types as follows:

In [56]:
struct Point3{T<:Real}
    x::T
    y::T
end
Base.:+(p::Point3, q::Point3) = Point3(p.x + q.x, p.y + q.y)
Base.zero{T}(::Type{Point3{T}}) = Point3(zero(T),zero(T))

Point3(3,4)

Point3{Int64}(3, 4)

Here, `Point3` is actually a family of subtypes `Point{T}` for different types `T`.   The notation `<:` in Julia means "is a subtype of", and hence `T<:Real` means that we are constraining `T` to be a `Real` type (a built-in *abstract type* in Julia that includes e.g. integers or floating point).

In [57]:
Point3(3,4) + Point3(5.6, 7.8)

Point3{Float64}(8.6, 11.8)

Now, let's make an array:

In [58]:
a3 = Point3.(a,a)

10000000-element Array{Point3{Float64},1}:
 Point3{Float64}(0.45576, 0.45576)    
 Point3{Float64}(0.199227, 0.199227)  
 Point3{Float64}(0.664066, 0.664066)  
 Point3{Float64}(0.106669, 0.106669)  
 Point3{Float64}(0.108969, 0.108969)  
 Point3{Float64}(0.146101, 0.146101)  
 Point3{Float64}(0.066834, 0.066834)  
 Point3{Float64}(0.933081, 0.933081)  
 Point3{Float64}(0.901608, 0.901608)  
 Point3{Float64}(0.680544, 0.680544)  
 Point3{Float64}(0.891394, 0.891394)  
 Point3{Float64}(0.128344, 0.128344)  
 Point3{Float64}(0.354404, 0.354404)  
 ⋮                                    
 Point3{Float64}(0.838992, 0.838992)  
 Point3{Float64}(0.940758, 0.940758)  
 Point3{Float64}(0.416696, 0.416696)  
 Point3{Float64}(0.17713, 0.17713)    
 Point3{Float64}(0.493455, 0.493455)  
 Point3{Float64}(0.44981, 0.44981)    
 Point3{Float64}(0.0298092, 0.0298092)
 Point3{Float64}(0.894299, 0.894299)  
 Point3{Float64}(0.270014, 0.270014)  
 Point3{Float64}(0.32509, 0.32509)    
 Point3{Float64}(0.19

In [59]:
typeof(a3)

Array{Point3{Float64},1}

Note that the type of this array is `Array{Point3{Float64},1}` (we could equivalently write this as `Vector{Point3{Float64}}`, since `Vector{T}` is a synonym for `Array{T,1}`).  You should learn a few things from this:

* An `Array{T,N}` in Julia is itself a parameterized type, parameterized by the element type `T` and the dimensionality `N`.

* Since the element type `T` is encoded in the `Array{T,N}` type, the element type does not need to be stored in each element.  That means that the `Array` is free to store an array of "inlined" elements, rather than an array of pointers to boxes.  (This is why `Array{Float64,1}` earlier could be stored in memory like a C `double*`.

* It is still important that the element type be `immutable`, since an array of mutable elements would still need to be an array of pointers (so that it could "notice" if another reference to an element mutates it).

In [61]:
@btime sum($a3)

  11.805 ms (0 allocations: 0 bytes)


Point3{Float64}(5.000915878780597e6, 5.000915878780597e6)

Hooray! It is again **only about 10ms**, the same time as our completely concrete and inflexible `Point2`.

In [62]:
p = Point3{Int8}(3,5)

Point3{Int8}(3, 5)

In [64]:
p = Point3{Integer}(3,Int8(5))

Point3{Integer}(3, 5)

In [65]:
typeof(p.x)

Int64

In [66]:
typeof(p.y)

Int8

In [67]:
3 + 7im

3 + 7im

In [68]:
typeof(3 + 7im)

Complex{Int64}

In [69]:
@which sqrt(3 + 4im)

sqrt(z::Complex) in Base at complex.jl:416

In [70]:
supertype(Point3{Int8})

Any

## Another type of "type instability"

In [1]:
function mysum_slow(a)
    s = 0
    for x in a
        s += x
    end
    return s
end

mysum_slow (generic function with 1 method)

In [2]:
mysum_slow([3,4,5])

12

In [3]:
mysum_slow([3.3,4,5])

12.3

In [6]:
@code_warntype(mysum_slow([3.3,4,5]))

Variables
  #self#::Core.Compiler.Const(mysum_slow, false)
  a::Array{Float64,1}
  s::Union{Float64, Int64}
  @_4::Union{Nothing, Tuple{Float64,Int64}}
  x::Float64

Body::Union{Float64, Int64}
1 ─       (s = 0)
│   %2  = a::Array{Float64,1}
│         (@_4 = Base.iterate(%2))
│   %4  = (@_4 === nothing)::Bool
│   %5  = Base.not_int(%4)::Bool
└──       goto #4 if not %5
2 ┄ %7  = @_4::Tuple{Float64,Int64}::Tuple{Float64,Int64}
│         (x = Core.getfield(%7, 1))
│   %9  = Core.getfield(%7, 2)::Int64
│         (s = s + x)
│         (@_4 = Base.iterate(%2, %9))
│   %12 = (@_4 === nothing)::Bool
│   %13 = Base.not_int(%12)::Bool
└──       goto #4 if not %13
3 ─       goto #2
4 ┄       return s


In [8]:
function mysum_fast(a)
    s = zero(eltype(a))
    for x in a
        s += x
    end
    return s
end

mysum_fast (generic function with 1 method)

In [10]:
@code_warntype mysum_fast([3.5,4,5])

Variables
  #self#::Core.Compiler.Const(mysum_fast, false)
  a::Array{Float64,1}
  s::Float64
  @_4::Union{Nothing, Tuple{Float64,Int64}}
  x::Float64

Body::Float64
1 ─ %1  = Main.eltype(a)::Core.Compiler.Const(Float64, false)
│         (s = Main.zero(%1))
│   %3  = a::Array{Float64,1}
│         (@_4 = Base.iterate(%3))
│   %5  = (@_4 === nothing)::Bool
│   %6  = Base.not_int(%5)::Bool
└──       goto #4 if not %6
2 ┄ %8  = @_4::Tuple{Float64,Int64}::Tuple{Float64,Int64}
│         (x = Core.getfield(%8, 1))
│   %10 = Core.getfield(%8, 2)::Int64
│         (s = s + x)
│         (@_4 = Base.iterate(%3, %10))
│   %13 = (@_4 === nothing)::Bool
│   %14 = Base.not_int(%13)::Bool
└──       goto #4 if not %14
3 ─       goto #2
4 ┄       return s


In [42]:
rand(3,3)

3×3 Array{Float64,2}:
 0.705275  0.479016  0.404006
 0.907342  0.834129  0.302675
 0.170249  0.203231  0.367633

In [47]:
zero([ones(3,3) for i = 1:10])

MethodError: MethodError: no method matching zero(::Type{Array{Float64,2}})
Closest candidates are:
  zero(!Matched::Type{Missing}) at missing.jl:103
  zero(!Matched::Type{LibGit2.GitHash}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\LibGit2\src\oid.jl:220
  zero(!Matched::Type{Pkg.Resolve.VersionWeight}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Resolve\versionweights.jl:15
  ...

In [24]:
?rand

search: rand randn transcode macroexpand @macroexpand @macroexpand1



```
rand([rng=GLOBAL_RNG], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:9` or `('x', "y", :z)`),
  * an `AbstractDict` or `AbstractSet` object,
  * a string (considered as a collection of characters), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to [`BigInt`](@ref)), to $[0, 1)$ for floating point numbers and to $[0, 1)+i[0, 1)]$ for complex floating point numbers;

`S` defaults to [`Float64`](@ref). When only one argument is passed besides the optional `rng` and is a `Tuple`, it is interpreted as a collection of values (`S`) and not as `dims`.

!!! compat "Julia 1.1"
    Support for `S` as a tuple requires at least Julia 1.1.


# Examples

```julia-repl
julia> rand(Int, 2)
2-element Array{Int64,1}:
 1339893410598768192
 1575814717733606317

julia> using Random

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
1=>2

julia> rand((2, 3))
3

julia> rand(Float64, (2, 3))
2×3 Array{Float64,2}:
 0.999717  0.0143835  0.540787
 0.696556  0.783855   0.938235
```

!!! note
    The complexity of `rand(rng, s::Union{AbstractDict,AbstractSet})` is linear in the length of `s`, unless an optimized method with constant complexity is available, which is the case for `Dict`, `Set` and `BitSet`. For more than a few calls, use `rand(rng, collect(s))` instead, or either `rand(rng, Dict(s))` or `rand(rng, Set(s))` as appropriate.



In [27]:
a = rand(10^7)
b=rand(Int64, 10^3)
a=[a;b];
a[end]

-7.907964995921943e18

In [17]:
@code_warntype mysum_slow(a)

Variables
  #self#::Core.Compiler.Const(mysum_slow, false)
  a::Array{Float64,1}
  s::Union{Float64, Int64}
  @_4::Union{Nothing, Tuple{Float64,Int64}}
  x::Float64

Body::Union{Float64, Int64}
1 ─       (s = 0)
│   %2  = a::Array{Float64,1}
│         (@_4 = Base.iterate(%2))
│   %4  = (@_4 === nothing)::Bool
│   %5  = Base.not_int(%4)::Bool
└──       goto #4 if not %5
2 ┄ %7  = @_4::Tuple{Float64,Int64}::Tuple{Float64,Int64}
│         (x = Core.getfield(%7, 1))
│   %9  = Core.getfield(%7, 2)::Int64
│         (s = s + x)
│         (@_4 = Base.iterate(%2, %9))
│   %12 = (@_4 === nothing)::Bool
│   %13 = Base.not_int(%12)::Bool
└──       goto #4 if not %13
3 ─       goto #2
4 ┄       return s


In [18]:
@code_warntype mysum_fast(a)

Variables
  #self#::Core.Compiler.Const(mysum_fast, false)
  a::Array{Float64,1}
  s::Float64
  @_4::Union{Nothing, Tuple{Float64,Int64}}
  x::Float64

Body::Float64
1 ─ %1  = Main.eltype(a)::Core.Compiler.Const(Float64, false)
│         (s = Main.zero(%1))
│   %3  = a::Array{Float64,1}
│         (@_4 = Base.iterate(%3))
│   %5  = (@_4 === nothing)::Bool
│   %6  = Base.not_int(%5)::Bool
└──       goto #4 if not %6
2 ┄ %8  = @_4::Tuple{Float64,Int64}::Tuple{Float64,Int64}
│         (x = Core.getfield(%8, 1))
│   %10 = Core.getfield(%8, 2)::Int64
│         (s = s + x)
│         (@_4 = Base.iterate(%3, %10))
│   %13 = (@_4 === nothing)::Bool
│   %14 = Base.not_int(%13)::Bool
└──       goto #4 if not %14
3 ─       goto #2
4 ┄       return s


In [22]:
@btime mysum_slow(a)

  11.317 ms (1 allocation: 16 bytes)


4.999148179613402e6

In [23]:

@btime mysum_fast(a)

  10.546 ms (1 allocation: 16 bytes)


4.999148179613402e6

In [46]:
mysum_fast([ones(3,3) for i = 1:10])

MethodError: MethodError: no method matching zero(::Type{Array{Float64,2}})
Closest candidates are:
  zero(!Matched::Type{Missing}) at missing.jl:103
  zero(!Matched::Type{LibGit2.GitHash}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\LibGit2\src\oid.jl:220
  zero(!Matched::Type{Pkg.Resolve.VersionWeight}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Resolve\versionweights.jl:15
  ...

In [44]:
sum([ones(3,3) for i = 1:10])

3×3 Array{Float64,2}:
 10.0  10.0  10.0
 10.0  10.0  10.0
 10.0  10.0  10.0

In [79]:
sum(Matrix{Float64}[])

LoadError: MethodError: no method matching zero(::Type{Array{Float64,2}})
Closest candidates are:
  zero(::Type{Base.LibGit2.GitHash}) at libgit2/oid.jl:106
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:82
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuild}) at pkg/resolve/versionweight.jl:124
  ...